openapi: 3.0.0
info:
  title: Movie Quotes Upgraded API
  description: Quotes from movies - is a platform where users can first register, then login and view quotes from movies.
  version: 1.0.0
servers:
  - url: http://localhost:8000/api
    description: local server
  - url: https://movie-quotes-back.aleqsandre-mchedlidze.redberryinternship.ge/api
    description: production server
paths:
  /quotes:
    $ref: "./_swagger/paths/quotes.yaml#/paths/~1quotes"
  /quote/add:
    $ref: "./_swagger/paths/quote.yaml#/paths/~1quote~1add"
  /quote/{quote}:
    $ref: "./_swagger/paths/quote.yaml#/paths/~1quote~1{quote}"
  /quote/{quote}/like:
    $ref: "./_swagger/paths/quote.yaml#/paths/~1quote~1{quote}~1like"
  /quote/{quote}/comment:
    $ref: "./_swagger/paths/quote.yaml#/paths/~1quote~1{quote}~1comment"
  /quote/{quote}/delete:
    $ref: "./_swagger/paths/quote.yaml#/paths/~1quote~1{quote}~1delete"
  /quote/{quote}/edit:
    $ref: "./_swagger/paths/quote.yaml#/paths/~1quote~1{quote}~1edit"
  /movies:
    $ref: "./_swagger/paths/movies.yaml#/paths/~1movies"
  /movies/add:
    $ref: "./_swagger/paths/movies.yaml#/paths/~1movies~1add"
  /movies/{user}:
      $ref: "./_swagger/paths/movies.yaml#/paths/~1movie~1{user}"
  /movies/search/{query}:
    $ref: "./_swagger/paths/movies.yaml#/paths/~1movies~1search~1{query}"
  /movie/{id}:
    $ref: "./_swagger/paths/movie.yaml#/paths/~1movie~1{id}"
  /movie/{id}/delete:
      $ref: "./_swagger/paths/movie.yaml#/paths/~1movie~1{id}~1delete"
  /movie/{id}/edit:
      $ref: "./_swagger/paths/movie.yaml#/paths/~1movie~1{id}~1edit"
  /user:
      $ref: "./_swagger/paths/user.yaml#/paths/~1user"
  /user/update:
      $ref: "./_swagger/paths/user.yaml#/paths/~1user~1update"
components:
  securitySchemes:
    santcumAuth:
      type: apiKey
      in: cookie
      name: X-CSRF-TOKEN
  schemas:
    User:
      allOf:
        - $ref: "./_swagger/schemas/user.yaml#/components/schemas/User"
    Comment:
      allOf:
        - $ref: "./_swagger/schemas/comment.yaml#/components/schemas/Comment"
    Genre:
      allOf:
        - $ref: "./_swagger/schemas/genre.yaml#/components/schemas/Genre"
    Like:
      allOf:
        - $ref: "./_swagger/schemas/like.yaml#/components/schemas/Like"
    Movie:
      allOf:
        - $ref: "./_swagger/schemas/movie.yaml#/components/schemas/Movie"
    Notification:
      allOf:
        - $ref: "./_swagger/schemas/notification.yaml#/components/schemas/Notification"
    Quote:
      allOf:
        - $ref: "./_swagger/schemas/quote.yaml#/components/schemas/Quote"
    GenreMovies:
      allOf:
        - $ref: "./_swagger/schemas/genre_movies.yaml#/components/schemas/GenreMovies"
